gpu_ids: '0'
output_dir: out/bert_base_wd_crf
mid_data_dir: data/crf_data/mid_data
raw_data_dir: data/crf_data
mode: train
task_type: crf
bert_dir: pretrained/bert-base-chinese
bert_type: bert_base
vote: false
train_epochs: 2
swa_start: 1
attack_train: ''
train_batch_size: 32
eval_batch_size: 32
dropout_prob: 0
max_seq_len: 200
lr: 2.0e-05
other_lr: 0.002
seed: 123
weight_decay: 0.01
loss_type: ls_ce
eval_model: true
use_fp16: false
use_type_embed: false
max_grad_norm: 1.0
warmup_proportion: 0.1
adam_epsilon: 1.0e-08
version: single
submit_dir: submit
ckpt_dir: ''
training_time: 0:07:12
score: 0.927
